### ISSUE TITLE
CLI subcommands

### ISSUE THREAD

**Issue by zrho** [CQCL/hugr#1311] opened 2024-07-16 10:56 UTC
Currently the `hugr-cli` binary can just validate hugrs. To allow for more tooling to be consolidated into the CLI tool, I propose we use subcommands (like cargo and git do). The current functionality can be moved to a `validate` subcommand, so that it would be run with `hugr validate [...]`. Clap has good support for this.

**Comment by ss2165** [comment] 2024-07-16 11:02
Closing as duplicate of #1207

**Closed by ss2165** 2024-07-16 11:02 UTC
